// Define TypeScript interfaces for icons and sizes
export interface IconsMap {
  [key: string]: string;
}

export interface SizeMap {
  [key: string]: number;
}

export const icons: IconsMap = {
  "duo-sun-bright": "/icons/svg/duotone/sun-bright.svg",
  "duo-moon-stars": "/icons/svg/duotone/moon-stars.svg",
  "duo-magnifying-glass": "/icons/svg/duotone/magnifying-glass.svg",
  "duo-user": "/icons/svg/duotone/user.svg",
  "duo-cart-shopping": "/icons/svg/duotone/cart-shopping.svg",
  "duo-bars": "/icons/svg/duotone/bars.svg",
  "duo-spinner-third": "/icons/svg/duotone/spinner-third.svg",
  "duo-lightbulb": "/icons/svg/duotone/lightbulb.svg",
  "duo-plus": "/icons/svg/duotone/plus.svg",
  "duo-minus": "/icons/svg/duotone/minus.svg",
  "duo-moon": "/icons/svg/duotone/moon.svg",
  "duo-calendar-day": "/icons/svg/duotone/calendar-day.svg",
  "duo-calendar-month": "/icons/svg/duotone/calendar-week.svg",
  "duo-calendar-year": "/icons/svg/duotone/calendar-days.svg",
  "duo-house": "/icons/svg/duotone/house.svg",
  "duo-circle-nodes": "/icons/svg/duotone/circle-nodes.svg",
  "reg-clock": "/icons/svg/regular/clock.svg",
  "reg-xmark": "/icons/svg/regular/xmark.svg",
  "duo-eye": "/icons/svg/duotone/eye.svg",
  "duo-eye-slash": "/icons/svg/duotone/eye-slash.svg",
  "duo-eye-low-vision": "/icons/svg/duotone/eye-low-vision.svg",
  "duo-link": "/icons/svg/duotone/link.svg",
  // New navigation icons
  "duo-book": "/icons/svg/duotone/book.svg",
  "duo-chart-line": "/icons/svg/duotone/chart-line.svg",
  "duo-seal-question": "/icons/svg/duotone/seal-question.svg",
  "duo-circle-user": "/icons/svg/duotone/circle-user.svg",
  "duo-book-user": "/icons/svg/duotone/book-user.svg",
  "duo-arrow-right-from-bracket": "/icons/svg/duotone/arrow-right-from-bracket.svg",
  "duo-chevron-down": "/icons/svg/duotone/chevron-down.svg",
  // Yoga-related icons
  "duo-person-praying": "/icons/svg/duotone/person-praying.svg",
  "duo-heart-pulse": "/icons/svg/duotone/heart-pulse.svg",
  "duo-calendar-check": "/icons/svg/duotone/calendar-check.svg",
  "duo-notes": "/icons/svg/duotone/notes.svg",
  "duo-scroll": "/icons/svg/duotone/scroll.svg",
  "duo-hands-praying": "/icons/svg/duotone/hands-praying.svg",
  "duo-user-crown": "/icons/svg/duotone/user-crown.svg",
  // Edit icon
  "duo-pen-to-square": "/icons/svg/duotone/pen-to-square.svg",
  "duo-circle-exclamation": "/icons/svg/duotone/circle-exclamation.svg",
  // Additional icons for replacing Lucide icons
  "duo-pencil": "/icons/svg/duotone/pencil.svg",
  "duo-trash": "/icons/svg/duotone/trash.svg",
  "duo-floppy-disk": "/icons/svg/duotone/floppy-disk.svg",
  "duo-xmark": "/icons/svg/duotone/xmark.svg",
  "duo-triangle-exclamation": "/icons/svg/duotone/triangle-exclamation.svg",
  // Icons for InvoicesSection
  "duo-download": "/icons/svg/duotone/download.svg",
  "duo-arrows-rotate": "/icons/svg/duotone/arrows-rotate.svg",
  "duo-file-lines": "/icons/svg/duotone/file-lines.svg",
  "duo-circle-xmark": "/icons/svg/duotone/circle-xmark.svg",
  "duo-arrow-up-right-from-square": "/icons/svg/duotone/arrow-up-right-from-square.svg",
  // Icons for PlanChangeModal
  "duo-circle-arrow-up": "/icons/svg/duotone/circle-arrow-up.svg",
  "duo-circle-arrow-down": "/icons/svg/duotone/circle-arrow-down.svg",
  // Icons for RefundsSection
  "duo-clock": "/icons/svg/duotone/clock.svg",
  "duo-circle-check": "/icons/svg/duotone/circle-check.svg",
  "duo-circle-question": "/icons/svg/duotone/circle-question.svg",
  "duo-calendar": "/icons/svg/duotone/calendar.svg",
  // Icons for SubscriptionManagement
  "duo-check": "/icons/svg/duotone/check.svg",
  "duo-arrows-spin": "/icons/svg/duotone/arrows-spin.svg",
  // Icons for TransactionsSection
  "duo-receipt": "/icons/svg/duotone/receipt.svg",
  "duo-arrow-right": "/icons/svg/duotone/arrow-right.svg",
  "duo-arrow-left": "/icons/svg/duotone/arrow-left.svg",
  // Icons for UpcomingPlanChanges
  "duo-calendar-alt": "/icons/svg/duotone/calendar.svg",
  "duo-cube": "/icons/svg/duotone/cube.svg",
  // Icons for UI components
  "duo-chevron-right": "/icons/svg/duotone/chevron-right.svg",
  "duo-chevron-left": "/icons/svg/duotone/chevron-left.svg",
  "duo-chevron-up": "/icons/svg/duotone/chevron-up.svg",
  "duo-more-horizontal": "/icons/svg/duotone/ellipsis.svg",
  "duo-grip-vertical": "/icons/svg/duotone/grip-lines-vertical.svg",
  "duo-circle": "/icons/svg/duotone/circle.svg",
  "duo-dot": "/icons/svg/duotone/circle-small.svg",
  "duo-panel-left": "/icons/svg/duotone/rectangle-vertical-history.svg",
  // Additional UI component icons
  "duo-search": "/icons/svg/duotone/magnifying-glass.svg",
  "duo-ellipsis-horizontal": "/icons/svg/duotone/ellipsis.svg",
  "duo-ellipsis-vertical": "/icons/svg/duotone/ellipsis-vertical.svg",
  "duo-x": "/icons/svg/duotone/xmark.svg",
  "duo-info": "/icons/svg/duotone/circle-info.svg",
  "duo-alert": "/icons/svg/duotone/circle-exclamation.svg",
  "duo-warning": "/icons/svg/duotone/triangle-exclamation.svg",
  "duo-success": "/icons/svg/duotone/circle-check.svg",
  "duo-caret-right": "/icons/svg/duotone/caret-right.svg",
  "duo-caret-left": "/icons/svg/duotone/caret-left.svg",
  "duo-caret-up": "/icons/svg/duotone/caret-up.svg",
  "duo-caret-down": "/icons/svg/duotone/caret-down.svg",
  // Debug and DataTable icons
  "duo-sliders": "/icons/svg/duotone/sliders.svg",
  "duo-gear": "/icons/svg/duotone/gear.svg",
  // DifficultySelector icons
  "duo-face-smile": "/icons/svg/duotone/face-smile.svg",
  "duo-dumbbell": "/icons/svg/duotone/dumbbell.svg",
  "duo-trophy": "/icons/svg/duotone/trophy.svg",
  "duo-split": "/icons/svg/duotone/split.svg",
  // PoseFeedback icons
  "duo-volume-high": "/icons/svg/duotone/volume-high.svg",
  "duo-volume-xmark": "/icons/svg/duotone/volume-xmark.svg",
  "duo-lock": "/icons/svg/duotone/lock.svg",
  "duo-arrow-up-right": "/icons/svg/duotone/arrow-up-right.svg",
  // PoseFeedbackModal icons
  "duo-message-square": "/icons/svg/duotone/comment.svg",
  // PracticePlayback icons
  "duo-loader": "/icons/svg/duotone/spinner-third.svg",
  "duo-refresh": "/icons/svg/duotone/arrows-rotate.svg",
  "duo-award": "/icons/svg/duotone/award.svg",
  "duo-timer": "/icons/svg/duotone/timer.svg",
  // PricingSection icons
  "duo-check-circle": "/icons/svg/duotone/circle-check.svg",
  "duo-arrow-up-circle": "/icons/svg/duotone/circle-arrow-up.svg",
  "duo-arrow-down-circle": "/icons/svg/duotone/circle-arrow-down.svg",
  // VideoSourceSelector icons
  "duo-camera": "/icons/svg/duotone/camera.svg",
  "duo-video": "/icons/svg/duotone/video.svg",
  // ContactUs page icons
  "duo-map-pin": "/icons/svg/duotone/map-pin.svg",
  "duo-phone": "/icons/svg/duotone/phone.svg",
  "duo-envelope": "/icons/svg/duotone/envelope.svg",
  // Home page icons
  "duo-book-alt": "/icons/svg/duotone/book-open.svg",
  "duo-activity-chart": "/icons/svg/duotone/chart-line-up.svg",
  "duo-star-bright": "/icons/svg/duotone/star-shooting.svg",
  "duo-users-group": "/icons/svg/duotone/users-between-lines.svg",
  "duo-target-bullseye": "/icons/svg/duotone/bullseye-arrow.svg",
  "duo-award-medal": "/icons/svg/duotone/award-simple.svg",
  // Payment status page icons
  "duo-circle-check-success": "/icons/svg/duotone/circle-check.svg",
  "duo-circle-xmark-error": "/icons/svg/duotone/circle-xmark.svg",
  "duo-spinner-loading": "/icons/svg/duotone/spinner.svg",
  // Pose detail page icons
  "duo-arrow-left-nav": "/icons/svg/duotone/arrow-left.svg",
  "duo-pencil-edit-alt": "/icons/svg/duotone/pencil-alt.svg",
  "duo-circle-exclamation-alert": "/icons/svg/duotone/circle-exclamation.svg",
  // PoseDetection page icons
  "duo-camera-detection": "/icons/svg/duotone/camera.svg",
  "duo-eye-show": "/icons/svg/duotone/eye.svg",
  "duo-eye-hide": "/icons/svg/duotone/eye-slash.svg",
  // Profile page icons
  "duo-user-circle": "/icons/svg/duotone/user-circle.svg",
  "duo-x-close": "/icons/svg/duotone/xmark.svg",
  // Refund policy page icons
  "duo-file": "/icons/svg/duotone/file.svg",
  "duo-file-pdf": "/icons/svg/duotone/file-pdf.svg",
  "duo-tower-broadcast": "/icons/svg/duotone/tower-broadcast.svg",
  // SinglePoseDetection page icons
  "duo-video-play": "/icons/svg/duotone/video.svg",
  "duo-pause-circle": "/icons/svg/duotone/pause.svg",
  "duo-upload-file": "/icons/svg/duotone/upload.svg",
  // Terms and conditions page icons
  "duo-file-alt": "/icons/svg/duotone/file-alt.svg",
  "duo-file-signature": "/icons/svg/duotone/file-signature.svg",
  // Yoga Poses
  "duo-caml": "/icons/svg/duotone-yoga-pose/camel.svg",
  "duo-char": "/icons/svg/duotone-yoga-pose/chair.svg",
  "duo-corps": "/icons/svg/duotone-yoga-pose/sivasana.svg",
  "duo-boat": "/icons/svg/duotone-yoga-pose/boatstraightlegs.svg",
  "duo-bang": "/icons/svg/duotone-yoga-pose/butterfly_.svg",
  "duo-bow": "/icons/svg/duotone-yoga-pose/bow.svg",
  "duo-brdg": "/icons/svg/duotone-yoga-pose/bridge.svg",
  "duo-crow": "/icons/svg/duotone-yoga-pose/crow.svg",
  "duo-ddog": "/icons/svg/duotone-yoga-pose/downdog.svg",
  "duo-esap": "/icons/svg/duotone-yoga-pose/extendedsideangle.svg",
  "duo-farm": "/icons/svg/duotone-yoga-pose/forearmstand.svg",
  "duo-fspl": "/icons/svg/duotone-yoga-pose/splits.svg",
  "duo-garl": "/icons/svg/duotone-yoga-pose/squat.svg",
  "duo-hlof": "/icons/svg/duotone-yoga-pose/seatedspinaltwist.svg",
  "duo-hmoon": "/icons/svg/duotone-yoga-pose/halfmoon.svg",
  "duo-hstd": "/icons/svg/duotone-yoga-pose/handstand.svg",
  "duo-lotu": "/icons/svg/duotone-yoga-pose/seatedORlotus.svg",
  "duo-olkp": "/icons/svg/duotone-yoga-pose/kingpigeon.svg",
  "duo-pigp": "/icons/svg/duotone-yoga-pose/pigeon.svg",
  "duo-plnk": "/icons/svg/duotone-yoga-pose/plank.svg",
  "duo-plow": "/icons/svg/duotone-yoga-pose/plow.svg",
  "duo-pyrm": "/icons/svg/duotone-yoga-pose/pyramid.svg",
  "duo-sfbp": "/icons/svg/duotone-yoga-pose/seatedforwardfold.svg",
  "duo-shld": "/icons/svg/duotone-yoga-pose/shoulderstand.svg",
  "duo-sspl": "/icons/svg/duotone-yoga-pose/straddlesplit.svg",
  "duo-sffp": "/icons/svg/duotone-yoga-pose/standingforwardfold.svg",
  "duo-tree": "/icons/svg/duotone-yoga-pose/tree.svg",
  "duo-udog": "/icons/svg/duotone-yoga-pose/updog.svg",
  "duo-war3": "/icons/svg/duotone-yoga-pose/warrior3.svg",
  "duo-war2": "/icons/svg/duotone-yoga-pose/warrior2.svg",
  "duo-war1": "/icons/svg/duotone-yoga-pose/warrior1.svg",
  "duo-whel": "/icons/svg/duotone-yoga-pose/wheel.svg",
  "duo-acmp": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-ausp": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-ctcw": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-cobr": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-cowf": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-cran": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-danc": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-durv": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-earp": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-easy": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-eang": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-etrp": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-fire": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-fish": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-flsp": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-frgp": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-flof": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-gate": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-hblf": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-hbow": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-hfrg": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-hufp": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-hbtoe": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-head": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-hkfb": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-hero": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-hors": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-kpig": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-lutw": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-loct": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-mar3": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-mar2": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-mar1": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-mar4": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-mntn": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-nams": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-peac": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-rstw": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-rbap": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-rhbt": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-rhero": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-rhmp": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-rsap": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-rtrp": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-scrw": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-splk": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-svsh": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-stff": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-tlfb": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-thun": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-visv": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-wasf": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-wlff": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  "duo-ysleep": "/icons/svg/duotone-yoga-pose/person-running-fast.svg",
  // Icons for NER training deck
  "duo-brain": "/icons/svg/duotone/brain.svg",
  "duo-graduation-cap": "/icons/svg/duotone/graduation-cap.svg",
  "duo-book-open": "/icons/svg/duotone/book-open.svg",
  "duo-list-check": "/icons/svg/duotone/list-check.svg",
  "duo-clipboard-list": "/icons/svg/duotone/clipboard-list.svg",
  "duo-brain-circuit": "/icons/svg/duotone/brain-circuit.svg",
  "duo-copy": "/icons/svg/duotone/copy.svg",
  "duo-shield-check": "/icons/svg/duotone/shield-check.svg",
  "duo-brackets-square": "/icons/svg/duotone/brackets-square.svg",
  "duo-gauge-high": "/icons/svg/duotone/gauge-high.svg",
  "duo-list-ol": "/icons/svg/duotone/list-ol.svg",
  "duo-arrow-trend-down": "/icons/svg/duotone/arrow-trend-down.svg",
  "duo-battery-quarter": "/icons/svg/duotone/battery-quarter.svg",
  "duo-check-double": "/icons/svg/duotone/check-double.svg",
  "duo-rocket": "/icons/svg/duotone/rocket.svg",
  // Icons for embedding quality deck
  "duo-broom": "/icons/svg/duotone/broom.svg",
  "duo-filter": "/icons/svg/duotone/filter.svg",
  "duo-scissors": "/icons/svg/duotone/scissors.svg",
  "duo-heading": "/icons/svg/duotone/heading.svg",
  "duo-eraser": "/icons/svg/duotone/eraser.svg",
  "duo-tags": "/icons/svg/duotone/tags.svg",
  "duo-table": "/icons/svg/duotone/table.svg",
  "duo-map": "/icons/svg/duotone/map.svg",
  "duo-flask": "/icons/svg/duotone/flask.svg",
  "duo-star": "/icons/svg/duotone/star.svg",
  // Icons for text classification deck
  "duo-bullseye": "/icons/svg/duotone/bullseye.svg",
  "duo-thumbs-up": "/icons/svg/duotone/thumbs-up.svg",
  "duo-wand-magic-sparkles": "/icons/svg/duotone/wand-magic-sparkles.svg",
  "duo-compass": "/icons/svg/duotone/compass.svg",
  "duo-scale-balanced": "/icons/svg/duotone/scale-balanced.svg",
  "duo-stream": "/icons/svg/duotone/water.svg",
  "duo-compress": "/icons/svg/duotone/compress.svg",
  "duo-balance-scale": "/icons/svg/duotone/balance-scale.svg",
  "duo-microchip": "/icons/svg/duotone/microchip.svg",
  "duo-ranking-star": "/icons/svg/duotone/ranking-star.svg",
  "duo-gears": "/icons/svg/duotone/gears.svg",
  "duo-network-wired": "/icons/svg/duotone/network-wired.svg",
  // Icons for NER metrics deck
  "duo-percent": "/icons/svg/duotone/percent.svg",
  "duo-clipboard-check": "/icons/svg/duotone/clipboard-check.svg",
  "duo-table-cells": "/icons/svg/duotone/table-cells.svg",
  "duo-circle-half-stroke": "/icons/svg/duotone/circle-half-stroke.svg",
  // Additional icons for deck files
  "duo-database": "/icons/svg/duotone/database.svg",
  "duo-robot": "/icons/svg/duotone/robot.svg",
  "duo-circle-1": "/icons/svg/duotone/circle-1.svg",
  "duo-circle-2": "/icons/svg/duotone/circle-2.svg",
  "duo-circle-3": "/icons/svg/duotone/circle-3.svg",
  "duo-circle-4": "/icons/svg/duotone/circle-4.svg",
  "duo-circle-5": "/icons/svg/duotone/circle-5.svg",
  "duo-circle-6": "/icons/svg/duotone/circle-6.svg",
  "duo-circle-7": "/icons/svg/duotone/circle-7.svg",
  "duo-circle-8": "/icons/svg/duotone/circle-8.svg",
  "duo-circle-9": "/icons/svg/duotone/circle-9.svg",
  "duo-diagram-project": "/icons/svg/duotone/diagram-project.svg",
  "duo-arrows-maximize": "/icons/svg/duotone/arrows-maximize.svg",
  "duo-dollar-sign": "/icons/svg/duotone/dollar-sign.svg",
  "duo-note-sticky": "/icons/svg/duotone/note-sticky.svg",
  "duo-sparkles": "/icons/svg/duotone/sparkles.svg",
  "duo-seedling": "/icons/svg/duotone/seedling.svg",
  "duo-layer-group": "/icons/svg/duotone/layer-group.svg",
  "duo-anchor": "/icons/svg/duotone/anchor.svg",
  "duo-code": "/icons/svg/duotone/code.svg",
  "duo-bolt": "/icons/svg/duotone/bolt.svg",
  "duo-cubes": "/icons/svg/duotone/cubes.svg",
  "duo-ruler": "/icons/svg/duotone/ruler.svg",
  "duo-paragraph": "/icons/svg/duotone/paragraph.svg",
  "duo-sitemap": "/icons/svg/duotone/sitemap.svg",
  "duo-wand-sparkles": "/icons/svg/duotone/wand-sparkles.svg",
  "duo-ruler-horizontal": "/icons/svg/duotone/ruler-horizontal.svg",
  "duo-window-maximize": "/icons/svg/duotone/window-maximize.svg",
  "duo-globe": "/icons/svg/duotone/globe.svg",
  "duo-toolbox": "/icons/svg/duotone/toolbox.svg",
  "duo-filter-circle-xmark": "/icons/svg/duotone/filter-circle-xmark.svg",
  "duo-leaf": "/icons/svg/duotone/leaf.svg",
  "duo-text-width": "/icons/svg/duotone/text-width.svg",
  "duo-hashtag": "/icons/svg/duotone/hashtag.svg",
  "duo-spell-check": "/icons/svg/duotone/spell-check.svg",
  "duo-scanner": "/icons/svg/duotone/scanner.svg",
  "duo-expand": "/icons/svg/duotone/expand.svg",
  "duo-microphone": "/icons/svg/duotone/microphone.svg",
  "duo-waveform-lines": "/icons/svg/duotone/waveform-lines.svg",
  "duo-plus-large": "/icons/svg/duotone/plus-large.svg",
  "duo-align-left": "/icons/svg/duotone/align-left.svg",
  "duo-text": "/icons/svg/duotone/text.svg",
  "duo-arrows-turn-to-dots": "/icons/svg/duotone/arrows-turn-to-dots.svg",
  "duo-image": "/icons/svg/duotone/image.svg",
  "duo-project-diagram": "/icons/svg/duotone/project-diagram.svg",
  "duo-chart-bar": "/icons/svg/duotone/chart-bar.svg",
  "duo-route": "/icons/svg/duotone/route.svg",
  "duo-puzzle-piece": "/icons/svg/duotone/puzzle-piece.svg",
  "duo-key": "/icons/svg/duotone/key.svg",
  "duo-tag": "/icons/svg/duotone/tag.svg",
  "duo-trash-can": "/icons/svg/duotone/trash-can.svg",
  "duo-file-contract": "/icons/svg/duotone/file-contract.svg",
  "duo-book-bookmark": "/icons/svg/duotone/book-bookmark.svg",
  "duo-face-meh": "/icons/svg/duotone/face-meh.svg",
  "duo-face-frown": "/icons/svg/duotone/face-frown.svg",
  "duo-tools": "/icons/svg/duotone/tools.svg",
  "duo-list": "/icons/svg/duotone/list.svg",
  "duo-folder-tree": "/icons/svg/duotone/folder-tree.svg",
  "duo-folder-open": "/icons/svg/duotone/folder-open.svg",
  "duo-message": "/icons/svg/duotone/message.svg",
  "duo-cloud": "/icons/svg/duotone/cloud.svg",
  "duo-code-branch": "/icons/svg/duotone/code-branch.svg",
  "duo-building": "/icons/svg/duotone/building.svg",
  "duo-shop": "/icons/svg/duotone/shop.svg",
  "duo-coins": "/icons/svg/duotone/coins.svg",
  "duo-unlock": "/icons/svg/duotone/unlock.svg",
  "duo-comments": "/icons/svg/duotone/comments.svg",
  "duo-gauge": "/icons/svg/duotone/gauge.svg",
  "duo-map-location": "/icons/svg/duotone/map-location.svg",
  "duo-server": "/icons/svg/duotone/server.svg",
  "duo-circle-info": "/icons/svg/duotone/circle-info.svg",
  "duo-info-circle": "/icons/svg/duotone/circle-info.svg",
  "duo-user-tag": "/icons/svg/duotone/user-tag.svg",
  "duo-highlighter": "/icons/svg/duotone/highlighter.svg",
  "duo-certificate": "/icons/svg/duotone/certificate.svg",
  "duo-diagram-nested": "/icons/svg/duotone/diagram-nested.svg",
  "duo-pen-ruler": "/icons/svg/duotone/pen-ruler.svg",
  "duo-magnifying-glass-chart": "/icons/svg/duotone/magnifying-glass-chart.svg",
  "duo-shield-halved": "/icons/svg/duotone/shield-halved.svg",
  "duo-heart": "/icons/svg/duotone/heart.svg",
  "duo-circle-dot": "/icons/svg/duotone/circle-dot.svg",
  "duo-arrow-right-arrow-left": "/icons/svg/duotone/arrow-right-arrow-left.svg",
  "duo-object-group": "/icons/svg/duotone/object-group.svg",
  "duo-diagram-next": "/icons/svg/duotone/diagram-next.svg",
  "duo-crosshairs": "/icons/svg/duotone/crosshairs.svg",
  "duo-scanner-keyboard": "/icons/svg/duotone/scanner-keyboard.svg",
};

export const size: SizeMap = {
  "2xs": 10,
  "xs": 12,
  "sm": 14,
  "lg": 20,
  "xl": 24,
  "2xl": 32,
  "1x": 16,
  "2x": 32,
  "3x": 48,
  "4x": 64,
  "5x": 80,
  "6x": 96,
  "7x": 112,
  "8x": 128,
  "9x": 144,
  "10x": 160,
};

// Export icon name and size name types for better type checking
export type IconName = keyof typeof icons;
export type SizeName = keyof typeof size;
